### ISSUE TITLE
Best way to pass in -L linker option

### ISSUE THREAD

**Issue by ghost** [adamheinrich/cm-makefile#3]
Hi there,

it looks like you're only expecting the user to specify a single linker script.  Is there a nicer way than the following to pass in the linker library directories using `-L` ?

```makefile
BIN = app
# snip for brevity
include cm-makefile/config.mk
include cm-makefile/rules.mk

LDFLAGS += -L./linker
```

**Comment by adamheinrich** [comment]
Hello, you can pass the `-L` option using the `INC` variable ([like here](https://github.com/adamheinrich/cm-makefile-examples/blob/master/stm32-libopencm3/Makefile#L7-L8)) which is then used both when building object files and linking the final binary:

```
BIN = app
INC = -L./linker

include cm-makefile/config.mk
include cm-makefile/rules.mk
```

We could maybe have something like separate `INC` and `INC_LD` but so far I have not ran into any issues mixing `-I` and `-L`.

**Comment by ghost** [comment]
Hi, okay, thanks for that.  Still need to specify the full path to the top level linker script but that's fine.
